env:
  node: true
  browser: true
  jest: true

root: true
parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript # this line does the trick
  - 'plugin:@typescript-eslint/recommended'

# extends:
#   - 'airbnb-base'

ignorePatterns:
  - '/dist'

settings:
  react:
    version: '16.13.1'

rules:
  # no-console: 1
  import/no-named-as-default: 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/no-empty-interface': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0

globals:
  Proxy: true
